apiVersion: v1
kind: Secret
metadata:
  name: github-config-morphacy
  # annotations:
  #   custom.argocd.argoproj.io/ignore-path: ".data.*"
type: Opaque
data:
  github_app_id: ""
  github_app_installation_id: ""
  github_app_private_key: ""
